### ISSUE TITLE
Upgraded to Jenkins 2.27 and the mesos plugin fails

### ISSUE THREAD

**Issue by sjcollin** [jenkinsci/mesos-plugin#269] opened 2016-10-27 22:15 UTC
Using latest plugin, Jenkins 2.27 fails with the following error.
Tried restarting, verify plugin, etc but it wasn't till I downgraded to Jenkins 2.25 that the problem was resolved.
Hostname obscured by replacing with HOSTNAME_REMOVED:

I1027 21:34:33.992662 26445 fetcher.cpp:424] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/2950fab3-50fb-4c18-905d-912058eb2ced-S24561","items":[{"action":"BYPASS_CACHE","uri":{"executable":false,"extract":false,"value":"http:\/\/HOSTNAME_REMOVED:8105\/jenkins\/cc\/jnlpJars\/slave.jar"}}],"sandbox_directory":"\/tmp\/mesos\/slaves\/2950fab3-50fb-4c18-905d-912058eb2ced-S24561\/frameworks\/2950fab3-50fb-4c18-905d-912058eb2ced-32648\/executors\/mesos-jenkins-0abe9864ffdd4594a416d8acc24e6c61-alm_mesos_cloud\/runs\/bf0c61d2-d637-409e-96ee-6330fc56ea57"}
I1027 21:34:33.994994 26445 fetcher.cpp:379] Fetching URI 'http://HOSTNAME_REMOVED:8105/jenkins/cc/jnlpJars/slave.jar'
I1027 21:34:33.995015 26445 fetcher.cpp:250] Fetching directly into the sandbox directory
I1027 21:34:33.995052 26445 fetcher.cpp:187] Fetching URI 'http://HOSTNAME_REMOVED:8105/jenkins/cc/jnlpJars/slave.jar'
I1027 21:34:33.995070 26445 fetcher.cpp:134] Downloading resource from 'http://HOSTNAME_REMOVED:8105/jenkins/cc/jnlpJars/slave.jar' to '/tmp/mesos/slaves/2950fab3-50fb-4c18-905d-912058eb2ced-S24561/frameworks/2950fab3-50fb-4c18-905d-912058eb2ced-32648/executors/mesos-jenkins-0abe9864ffdd4594a416d8acc24e6c61-alm_mesos_cloud/runs/bf0c61d2-d637-409e-96ee-6330fc56ea57/slave.jar'
I1027 21:34:34.013631 26445 fetcher.cpp:456] Fetched 'http://HOSTNAME_REMOVED:8105/jenkins/cc/jnlpJars/slave.jar' to '/tmp/mesos/slaves/2950fab3-50fb-4c18-905d-912058eb2ced-S24561/frameworks/2950fab3-50fb-4c18-905d-912058eb2ced-32648/executors/mesos-jenkins-0abe9864ffdd4594a416d8acc24e6c61-alm_mesos_cloud/runs/bf0c61d2-d637-409e-96ee-6330fc56ea57/slave.jar'
I1027 21:34:34.188441 26472 exec.cpp:143] Version: 0.28.2
I1027 21:34:34.191814 26476 exec.cpp:217] Executor registered on slave 2950fab3-50fb-4c18-905d-912058eb2ced-S24561
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main createEngine
INFO: Setting up slave: mesos-jenkins-0abe9864ffdd4594a416d8acc24e6c61-alm_mesos_cloud
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener <init>
INFO: Jenkins agent is running in headless mode.
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Locating server among [http://HOSTNAME_REMOVED:8105/jenkins/cc/]
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Agent discovery successful
  Agent address: HOSTNAME_REMOVED
  Agent port:    11169
  Identity:      85:8c:62:55:b5:af:38:0d:5a:82:60:68:c0:54:78:1f
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Handshaking
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to HOSTNAME_REMOVED:11169
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-connect not supported, skipping
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP4-plaintext not supported, skipping
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Server reports protocol JNLP3-connect not supported, skipping
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP2-connect
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP2-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at hudson.remoting.Engine.innerRun(Engine.java:415)
    at hudson.remoting.Engine.run(Engine.java:280)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
    at org.jenkinsci.remoting.engine.JnlpProtocol2Handler.sendHandshake(JnlpProtocol2Handler.java:134)
    at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
    at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at hudson.remoting.Engine$1$1.run(Engine.java:94)
    at java.lang.Thread.run(Thread.java:745)

Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Connecting to slc10usf.us.oracle.com:11169
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Trying protocol: JNLP-connect
Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener status
INFO: Protocol JNLP-connect encountered an unexpected exception
java.util.concurrent.ExecutionException: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at hudson.remoting.Engine.innerRun(Engine.java:415)
    at hudson.remoting.Engine.run(Engine.java:280)
Caused by: org.jenkinsci.remoting.protocol.impl.ConnectionRefusalException: Server didn't accept the handshake: 
    at org.jenkinsci.remoting.engine.JnlpProtocol1Handler.sendHandshake(JnlpProtocol1Handler.java:121)
    at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:162)
    at org.jenkinsci.remoting.engine.LegacyJnlpProtocolHandler$2.call(LegacyJnlpProtocolHandler.java:158)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at hudson.remoting.Engine$1$1.run(Engine.java:94)
    at java.lang.Thread.run(Thread.java:745)

Oct 27, 2016 9:34:37 PM hudson.remoting.jnlp.Main$CuiListener error
SEVERE: The server rejected the connection: None of the protocols were accepted
java.lang.Exception: The server rejected the connection: None of the protocols were accepted
    at hudson.remoting.Engine.onConnectionRejected(Engine.java:476)
    at hudson.remoting.Engine.innerRun(Engine.java:440)
    at hudson.remoting.Engine.run(Engine.java:280)

**Comment by nikore** [comment] 2016-10-28 23:38
I can also confirm this error; reverting to 2.26 worked fine; I saw a similar issue with the vspere plugin https://issues.jenkins-ci.org/browse/JENKINS-39232 

it looks like it might need to be changed to inheirt from the delegated launcher instead of being a Launcher its self (based on https://github.com/jenkinsci/vsphere-cloud-plugin/pull/59/files) but it also seems like Jenkins is working on away to make the new JNLP stuff compatible with plugins like this.

**Comment by sjcollin** [comment] 2016-11-18 15:35
Appears to still fail on latest Jenkins 2.32

**Comment by crunchyjohn** [comment] 2016-11-30 18:24
I see the same thing on Jenkins 2.34

**Comment by sjcollin** [comment] 2016-12-07 18:18
Appears to still fail on latest Jenkins 2.35

**Comment by maselvaraj** [comment] 2016-12-08 06:33
I will check and fix this.

**Comment by maselvaraj** [comment] 2016-12-08 23:48
@sjcollin @Reamer @nikore I've raised a PR to use JNLPLauncher instead of ComputerLauncher. I was able to launch slaves with Mesos. Would you be able to help test this ? 
You can build the plugin from my fork https://github.com/maselvaraj/mesos-plugin 'master' branch

Thanks!

**Comment by raghu999** [comment] 2016-12-29 16:53
We are also seeing the same issue with jenkins 2.3.8 Mesos plugin version 1.13

**Comment by Reamer** [comment] 2017-01-02 14:55
Hi,
I've compiled and installed the current master 277d098fa699aa46473c13629f9ef46fc7276d12 which contains @maselvaraj Pull-Request. It works!
I use current Jenkins-LTS-Version 2.32.1

It would be nice if someone can release a new plugin to https://wiki.jenkins-ci.org/display/JENKINS/Mesos+Plugin

Best Regards
Reamer

**Comment by maselvaraj** [comment] 2017-01-02 19:15
Thanks @Reamer. I will do a regression and cut a release tomorrow.

**Comment by raghu999** [comment] 2017-01-03 15:30
Yes, we also tried compiling with @maselvaraj pull request.I can confirm it works for us too.

**Comment by maselvaraj** [comment] 2017-01-04 19:04
Thanks everyone for reporting this and testing the fix. Released 0.14.0 which includes a fix for this. Release 0.14.0 is already available in Jenkins update center.

**Closed by maselvaraj** 2017-01-04 19:04 UTC
