### ISSUE TITLE
Multiple Mesos Clouds configured causes frameworks to restart on config change

### ISSUE THREAD

**Issue by damomurf** [jenkinsci/mesos-plugin#270] opened 2016-10-28 05:07 UTC
If more than one Mesos Cloud is configured and each is registered as a frameworks in its corresponding Mesos cluster, saving settings causes both frameworks to restart every time, killing all running jobs on both. Adding the second cloud configuration with the first in place and already registered does not exhibit this behaviour, only changing configuration _after_ both are already registered.

```
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.MesosCloud restartMesos
INFO: Mesos master changed, restarting the scheduler
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler stop
INFO: Stopping Mesos driver.
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler <init>
INFO: JenkinsScheduler instantiated with jenkins http://jenkins.domain and mesos zk://.../mesos
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
INFO: The Mesos driver was stopped.
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler init
INFO: Initializing the Mesos driver with options
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler registered
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.MesosCloud restartMesos
INFO: Mesos master changed, restarting the scheduler
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler stop
INFO: Stopping Mesos driver.
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler <init>
INFO: JenkinsScheduler instantiated with jenkins http://jenkins.domain and mesos zk://.../mesos
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
INFO: The Mesos driver was stopped.
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler init
INFO: Initializing the Mesos driver with options
Oct 28, 2016 1:00:26 AM org.jenkinsci.plugins.mesos.JenkinsScheduler registered
```

**Comment by jeschkies** [comment] 2019-11-11 13:42
@damomurf, 1.0 does not support multiple clouds due to the limitations of the Mesos Java client. However, 2.0 uses the Mesos v1 HTTP API and should support multiple clouds. Could you try it out?

**Comment by damomurf** [comment] 2019-11-11 22:01
@jeschkies Unfortunately I haven’t had access to Mesos clusters for quite some time so can’t really help you there.

**Comment by jeschkies** [comment] 2019-11-12 09:20
I close it as cannot reproduce then 🙂

**Closed by jeschkies** 2019-11-12 09:20 UTC
