### ISSUE TITLE
Jenkins workflow plugin and mesos-plugin

### ISSUE THREAD

**Issue by digitalrinaldo** [jenkinsci/mesos-plugin#150] opened 2015-07-09 03:23 UTC
The jenkins workflow plugin has many advantages over the previous approaches.  I did not see the mesos plugin listed as working with workflow.

**Comment by maselvaraj** [comment] 2015-07-09 04:17
duplicate of https://github.com/jenkinsci/mesos-plugin/issues/151

**Closed by maselvaraj** 2015-07-09 04:17 UTC
