### ISSUE TITLE
Does it work with Jenkins LTS 1.609.1 ?

### ISSUE THREAD

**Issue by geoffroyjabouley** [jenkinsci/mesos-plugin#143] opened 2015-07-02 07:17 UTC
Hello

i am in the progress of upgrading the Jenkins core version of our infrastructure. We were previously using Jenkins LTS 1.580.3.

I am right now stuck at version 1.596.3, which is the last one working with my mesos 0.22.1 setup + jenkins-mesos v0.8.0-SNAPSHOT from yesterday.

When i upgrade to Jenkins LTS 1.609.1, Jenkins is unable to correctly starts a mesos slaves:
- The computer is created on Jenkins
- The Jenkins mesos framework registers with Mesos
- A new mesos task is started
- The task fails with the following error in the mesos sandbox log:

```
I0701 16:52:12.720751 23089 fetcher.cpp:214] Fetching URI 'http://10.195.96.236:20000/jnlpJars/slave.jar'
I0701 16:52:12.720882 23089 fetcher.cpp:125] Fetching URI 'http://10.195.96.236:20000/jnlpJars/slave.jar' with os::net
I0701 16:52:12.720896 23089 fetcher.cpp:135] Downloading 'http://10.195.96.236:20000/jnlpJars/slave.jar' to '/tmp/mesos/slaves/20150701-155911-3965764362-5050-124421-S0/frameworks/20150701-155911-3965764362-5050-124421-0006/executors/mesos-jenkins-a6b74dc7-d4d5-45b2-8895-99fbaecba2b0/runs/0420cf2b-3eeb-4bea-b586-0a71f9d3e8f9/slave.jar'
I0701 16:52:12.749831 23089 fetcher.cpp:329] Skipped extracting path '/tmp/mesos/slaves/20150701-155911-3965764362-5050-124421-S0/frameworks/20150701-155911-3965764362-5050-124421-0006/executors/mesos-jenkins-a6b74dc7-d4d5-45b2-8895-99fbaecba2b0/runs/0420cf2b-3eeb-4bea-b586-0a71f9d3e8f9/slave.jar'
I0701 16:52:13.131577 23113 exec.cpp:132] Version: 0.22.1
I0701 16:52:13.135164 23130 exec.cpp:206] Executor registered on slave 20150701-155911-3965764362-5050-124421-S0
Exception in thread "main" java.io.IOException: Failing to obtain http://10.195.96.236:20000/computer/mesos-jenkins-a6b74dc7-d4d5-45b2-8895-99fbaecba2b0/slave-agent.jnlp?encrypt=true
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:334)
	at hudson.remoting.Launcher.run(Launcher.java:219)
	at hudson.remoting.Launcher.main(Launcher.java:192)
Caused by: java.io.IOException: Failed to load http://10.195.96.236:20000/computer/mesos-jenkins-a6b74dc7-d4d5-45b2-8895-99fbaecba2b0/slave-agent.jnlp?encrypt=true: 504 Gateway Timeout
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:275)
	... 2 more
```

I had never noticed that the jnlp-agent url had an attribute field "encrypt".

I first thought it was a network related issue on my side (504 Gateway Timeout), but on the exact same machine/setup, all jenkins LTS versions from 1.580.3 to 1.596.3 are working fine.

Does anybody is successfully using Mesos plugin with the latest Jenkins LTS 1.609.1?

**Comment by maselvaraj** [comment] 2015-07-02 08:43
@geoffroyjabouley Not sure if this is related to this issue : https://rm.cloudbees.com/issues/2489 

Is security enabled in your Jenkins ? If yes, can you try giving overall READ access for anonymous and try ?

**Comment by geoffroyjabouley** [comment] 2015-07-02 11:58
Hello

Yes security is enabled, using local jenkins database, and matrix based security.

Anonymous has overall READ access:
```
    <permission>hudson.model.Hudson.Read:anonymous</permission>
```

I am also a bit surprised that sometimes Slaves computers are created using the anonymous user, and sometimes using the SYSTEM user

![slave_anonymous](https://cloud.githubusercontent.com/assets/2145297/8476507/65132016-20c2-11e5-95ec-08b7114c3cf4.png)

![slave_system](https://cloud.githubusercontent.com/assets/2145297/8476511/6a73422a-20c2-11e5-8584-c83a70d43461.png)

**Comment by geoffroyjabouley** [comment] 2015-07-07 15:37
Hello
has anybody managed to used the mesos plugin on a Jenkins 1.609.1 LTS version with security enabled (login/pass to access to admin jenkins functions)?

**Comment by tangicolin** [comment] 2015-09-04 07:56
Test without security enable and problem is the same. On 1.609.3 i have the same error : 

I0904 09:52:45.375186 29817 fetcher.cpp:214] Fetching URI 'http://10.195.30.19:31021/jnlpJars/slave.jar'
I0904 09:52:45.375265 29817 fetcher.cpp:125] Fetching URI 'http://10.195.30.19:31021/jnlpJars/slave.jar' with os::net
I0904 09:52:45.375272 29817 fetcher.cpp:135] Downloading 'http://10.195.30.19:31021/jnlpJars/slave.jar' to '/tmp/mesos/slaves/20150813-105908-337560330-5050-3891-S1/frameworks/20150826-103430-320783114-5050-21584-0473/executors/mesos-jenkins-f2c0ea80-d02f-47df-a6e1-721e4eb3830e/runs/bfa50d0d-4c7a-4cc2-8a23-10d7e48c9398/slave.jar'
I0904 09:52:45.381439 29817 fetcher.cpp:329] Skipped extracting path '/tmp/mesos/slaves/20150813-105908-337560330-5050-3891-S1/frameworks/20150826-103430-320783114-5050-21584-0473/executors/mesos-jenkins-f2c0ea80-d02f-47df-a6e1-721e4eb3830e/runs/bfa50d0d-4c7a-4cc2-8a23-10d7e48c9398/slave.jar'
I0904 09:52:45.750459 29852 exec.cpp:132] Version: 0.22.1
I0904 09:52:45.758150 29868 exec.cpp:206] Executor registered on slave 20150813-105908-337560330-5050-3891-S1
Exception in thread "main" java.io.IOException: Failing to obtain http://10.195.30.19:31021/computer/mesos-jenkins-f2c0ea80-d02f-47df-a6e1-721e4eb3830e/slave-agent.jnlp
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:334)
	at hudson.remoting.Launcher.run(Launcher.java:219)
	at hudson.remoting.Launcher.main(Launcher.java:192)
Caused by: java.io.IOException: Failed to load http://10.195.30.19:31021/computer/mesos-jenkins-f2c0ea80-d02f-47df-a6e1-721e4eb3830e/slave-agent.jnlp: 504 Gateway Timeout
	at hudson.remoting.Launcher.parseJnlpArguments(Launcher.java:275)

**Comment by tangicolin** [comment] 2015-09-04 09:06
Find the issue, is related to a new jenkins feature that the slave.jar honor the http_proxy env var but not the no_proxy env var (see https://issues.jenkins-ci.org/browse/JENKINS-28086).

**Comment by tangicolin** [comment] 2015-09-04 09:24
I have found a pull request that fix this issue : https://github.com/jenkinsci/remoting/pull/55
Should wait to be merged

**Comment by carlossg** [comment] 2016-07-18 08:14
Already fixed in jenkins core

**Closed by carlossg** 2016-07-18 08:14 UTC
